url: https://up-to.date
baseurl: ''
title: UpToDate
description: >-
  Keep track of the latest releases of your favorite libraries, frameworks and
  programming languages

plugins:
  - jekyll-postcss

postcss:
  cache: false
